//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.SOAPCSharpHeroeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPCSharpHeroeService.HeroeServiceSoap")]
    public interface HeroeServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje SelectRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpHeroeService.SelectResponse Select(Business.SOAPCSharpHeroeService.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.SelectResponse> SelectAsync(Business.SOAPCSharpHeroeService.SelectRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje InsertRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpHeroeService.InsertResponse Insert(Business.SOAPCSharpHeroeService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.InsertResponse> InsertAsync(Business.SOAPCSharpHeroeService.InsertRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje UpdateRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpHeroeService.UpdateResponse Update(Business.SOAPCSharpHeroeService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.UpdateResponse> UpdateAsync(Business.SOAPCSharpHeroeService.UpdateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje DeleteRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpHeroeService.DeleteResponse Delete(Business.SOAPCSharpHeroeService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.DeleteResponse> DeleteAsync(Business.SOAPCSharpHeroeService.DeleteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ListRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpHeroeService.ListResponse List(Business.SOAPCSharpHeroeService.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.ListResponse> ListAsync(Business.SOAPCSharpHeroeService.ListRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje TotalRecordsRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpHeroeService.TotalRecordsResponse TotalRecords(Business.SOAPCSharpHeroeService.TotalRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.TotalRecordsResponse> TotalRecordsAsync(Business.SOAPCSharpHeroeService.TotalRecordsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ExcelRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpHeroeService.ExcelResponse Excel(Business.SOAPCSharpHeroeService.ExcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excel", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.ExcelResponse> ExcelAsync(Business.SOAPCSharpHeroeService.ExcelRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje PDFRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpHeroeService.PDFResponse PDF(Business.SOAPCSharpHeroeService.PDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PDF", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.PDFResponse> PDFAsync(Business.SOAPCSharpHeroeService.PDFRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SOAPKeyAuth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroePDFDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] FileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("FileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeServicePDF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private HeroePDFDTO pDFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public HeroePDFDTO PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
                this.RaisePropertyChanged("PDF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titleField;
        
        private string[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("Messages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeExcelDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] FileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("FileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeServiceExcel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private HeroeExcelDTO excelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public HeroeExcelDTO Excel {
            get {
                return this.excelField;
            }
            set {
                this.excelField = value;
                this.RaisePropertyChanged("Excel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeServiceTotalRecords : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private long totalRecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long TotalRecords {
            get {
                return this.totalRecordsField;
            }
            set {
                this.totalRecordsField = value;
                this.RaisePropertyChanged("TotalRecords");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeServiceList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private Heroe[] heroesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Heroe[] Heroes {
            get {
                return this.heroesField;
            }
            set {
                this.heroesField = value;
                this.RaisePropertyChanged("Heroes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Heroe : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string homeField;
        
        private string appearanceField;
        
        private string descriptionField;
        
        private string imgBase64StringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
                this.RaisePropertyChanged("Home");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Appearance {
            get {
                return this.appearanceField;
            }
            set {
                this.appearanceField = value;
                this.RaisePropertyChanged("Appearance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ImgBase64String {
            get {
                return this.imgBase64StringField;
            }
            set {
                this.imgBase64StringField = value;
                this.RaisePropertyChanged("ImgBase64String");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeListDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("PageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeServiceDelete : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private bool deleteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("Delete");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeServiceUpdate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private bool updateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
                this.RaisePropertyChanged("Update");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeServiceInsert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private Heroe heroeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Heroe Heroe {
            get {
                return this.heroeField;
            }
            set {
                this.heroeField = value;
                this.RaisePropertyChanged("Heroe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeInsertDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string homeField;
        
        private string appearanceField;
        
        private string descriptionField;
        
        private string imgBase64StringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
                this.RaisePropertyChanged("Home");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Appearance {
            get {
                return this.appearanceField;
            }
            set {
                this.appearanceField = value;
                this.RaisePropertyChanged("Appearance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ImgBase64String {
            get {
                return this.imgBase64StringField;
            }
            set {
                this.imgBase64StringField = value;
                this.RaisePropertyChanged("ImgBase64String");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeroeServiceSelect : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private Heroe heroeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Heroe Heroe {
            get {
                return this.heroeField;
            }
            set {
                this.heroeField = value;
                this.RaisePropertyChanged("Heroe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Select", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public SelectRequest() {
        }
        
        public SelectRequest(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, int id) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeServiceSelect SelectResult;
        
        public SelectResponse() {
        }
        
        public SelectResponse(Business.SOAPCSharpHeroeService.HeroeServiceSelect SelectResult) {
            this.SelectResult = SelectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeInsertDTO heroeInsertDTO;
        
        public InsertRequest() {
        }
        
        public InsertRequest(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpHeroeService.HeroeInsertDTO heroeInsertDTO) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.heroeInsertDTO = heroeInsertDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeServiceInsert InsertResult;
        
        public InsertResponse() {
        }
        
        public InsertResponse(Business.SOAPCSharpHeroeService.HeroeServiceInsert InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.Heroe heroe;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpHeroeService.Heroe heroe) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.heroe = heroe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeServiceUpdate UpdateResult;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Business.SOAPCSharpHeroeService.HeroeServiceUpdate UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, int id) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeServiceDelete DeleteResult;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(Business.SOAPCSharpHeroeService.HeroeServiceDelete DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeListDTO heroeListDTO;
        
        public ListRequest() {
        }
        
        public ListRequest(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpHeroeService.HeroeListDTO heroeListDTO) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.heroeListDTO = heroeListDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeServiceList ListResult;
        
        public ListResponse() {
        }
        
        public ListResponse(Business.SOAPCSharpHeroeService.HeroeServiceList ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TotalRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TotalRecordsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth;
        
        public TotalRecordsRequest() {
        }
        
        public TotalRecordsRequest(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth) {
            this.SOAPKeyAuth = SOAPKeyAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TotalRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TotalRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeServiceTotalRecords TotalRecordsResult;
        
        public TotalRecordsResponse() {
        }
        
        public TotalRecordsResponse(Business.SOAPCSharpHeroeService.HeroeServiceTotalRecords TotalRecordsResult) {
            this.TotalRecordsResult = TotalRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Excel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExcelRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth;
        
        public ExcelRequest() {
        }
        
        public ExcelRequest(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth) {
            this.SOAPKeyAuth = SOAPKeyAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeServiceExcel ExcelResult;
        
        public ExcelResponse() {
        }
        
        public ExcelResponse(Business.SOAPCSharpHeroeService.HeroeServiceExcel ExcelResult) {
            this.ExcelResult = ExcelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PDF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PDFRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth;
        
        public PDFRequest() {
        }
        
        public PDFRequest(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth) {
            this.SOAPKeyAuth = SOAPKeyAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PDFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpHeroeService.HeroeServicePDF PDFResult;
        
        public PDFResponse() {
        }
        
        public PDFResponse(Business.SOAPCSharpHeroeService.HeroeServicePDF PDFResult) {
            this.PDFResult = PDFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HeroeServiceSoapChannel : Business.SOAPCSharpHeroeService.HeroeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeroeServiceSoapClient : System.ServiceModel.ClientBase<Business.SOAPCSharpHeroeService.HeroeServiceSoap>, Business.SOAPCSharpHeroeService.HeroeServiceSoap {
        
        public HeroeServiceSoapClient() {
        }
        
        public HeroeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeroeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpHeroeService.SelectResponse Business.SOAPCSharpHeroeService.HeroeServiceSoap.Select(Business.SOAPCSharpHeroeService.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public Business.SOAPCSharpHeroeService.HeroeServiceSelect Select(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, int id) {
            Business.SOAPCSharpHeroeService.SelectRequest inValue = new Business.SOAPCSharpHeroeService.SelectRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.id = id;
            Business.SOAPCSharpHeroeService.SelectResponse retVal = ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).Select(inValue);
            return retVal.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.SelectResponse> Business.SOAPCSharpHeroeService.HeroeServiceSoap.SelectAsync(Business.SOAPCSharpHeroeService.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.SelectResponse> SelectAsync(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, int id) {
            Business.SOAPCSharpHeroeService.SelectRequest inValue = new Business.SOAPCSharpHeroeService.SelectRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.id = id;
            return ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpHeroeService.InsertResponse Business.SOAPCSharpHeroeService.HeroeServiceSoap.Insert(Business.SOAPCSharpHeroeService.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public Business.SOAPCSharpHeroeService.HeroeServiceInsert Insert(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpHeroeService.HeroeInsertDTO heroeInsertDTO) {
            Business.SOAPCSharpHeroeService.InsertRequest inValue = new Business.SOAPCSharpHeroeService.InsertRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.heroeInsertDTO = heroeInsertDTO;
            Business.SOAPCSharpHeroeService.InsertResponse retVal = ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).Insert(inValue);
            return retVal.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.InsertResponse> Business.SOAPCSharpHeroeService.HeroeServiceSoap.InsertAsync(Business.SOAPCSharpHeroeService.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.InsertResponse> InsertAsync(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpHeroeService.HeroeInsertDTO heroeInsertDTO) {
            Business.SOAPCSharpHeroeService.InsertRequest inValue = new Business.SOAPCSharpHeroeService.InsertRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.heroeInsertDTO = heroeInsertDTO;
            return ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpHeroeService.UpdateResponse Business.SOAPCSharpHeroeService.HeroeServiceSoap.Update(Business.SOAPCSharpHeroeService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public Business.SOAPCSharpHeroeService.HeroeServiceUpdate Update(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpHeroeService.Heroe heroe) {
            Business.SOAPCSharpHeroeService.UpdateRequest inValue = new Business.SOAPCSharpHeroeService.UpdateRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.heroe = heroe;
            Business.SOAPCSharpHeroeService.UpdateResponse retVal = ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).Update(inValue);
            return retVal.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.UpdateResponse> Business.SOAPCSharpHeroeService.HeroeServiceSoap.UpdateAsync(Business.SOAPCSharpHeroeService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.UpdateResponse> UpdateAsync(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpHeroeService.Heroe heroe) {
            Business.SOAPCSharpHeroeService.UpdateRequest inValue = new Business.SOAPCSharpHeroeService.UpdateRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.heroe = heroe;
            return ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpHeroeService.DeleteResponse Business.SOAPCSharpHeroeService.HeroeServiceSoap.Delete(Business.SOAPCSharpHeroeService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public Business.SOAPCSharpHeroeService.HeroeServiceDelete Delete(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, int id) {
            Business.SOAPCSharpHeroeService.DeleteRequest inValue = new Business.SOAPCSharpHeroeService.DeleteRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.id = id;
            Business.SOAPCSharpHeroeService.DeleteResponse retVal = ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).Delete(inValue);
            return retVal.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.DeleteResponse> Business.SOAPCSharpHeroeService.HeroeServiceSoap.DeleteAsync(Business.SOAPCSharpHeroeService.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.DeleteResponse> DeleteAsync(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, int id) {
            Business.SOAPCSharpHeroeService.DeleteRequest inValue = new Business.SOAPCSharpHeroeService.DeleteRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.id = id;
            return ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpHeroeService.ListResponse Business.SOAPCSharpHeroeService.HeroeServiceSoap.List(Business.SOAPCSharpHeroeService.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public Business.SOAPCSharpHeroeService.HeroeServiceList List(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpHeroeService.HeroeListDTO heroeListDTO) {
            Business.SOAPCSharpHeroeService.ListRequest inValue = new Business.SOAPCSharpHeroeService.ListRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.heroeListDTO = heroeListDTO;
            Business.SOAPCSharpHeroeService.ListResponse retVal = ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).List(inValue);
            return retVal.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.ListResponse> Business.SOAPCSharpHeroeService.HeroeServiceSoap.ListAsync(Business.SOAPCSharpHeroeService.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.ListResponse> ListAsync(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpHeroeService.HeroeListDTO heroeListDTO) {
            Business.SOAPCSharpHeroeService.ListRequest inValue = new Business.SOAPCSharpHeroeService.ListRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.heroeListDTO = heroeListDTO;
            return ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).ListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpHeroeService.TotalRecordsResponse Business.SOAPCSharpHeroeService.HeroeServiceSoap.TotalRecords(Business.SOAPCSharpHeroeService.TotalRecordsRequest request) {
            return base.Channel.TotalRecords(request);
        }
        
        public Business.SOAPCSharpHeroeService.HeroeServiceTotalRecords TotalRecords(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpHeroeService.TotalRecordsRequest inValue = new Business.SOAPCSharpHeroeService.TotalRecordsRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            Business.SOAPCSharpHeroeService.TotalRecordsResponse retVal = ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).TotalRecords(inValue);
            return retVal.TotalRecordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.TotalRecordsResponse> Business.SOAPCSharpHeroeService.HeroeServiceSoap.TotalRecordsAsync(Business.SOAPCSharpHeroeService.TotalRecordsRequest request) {
            return base.Channel.TotalRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.TotalRecordsResponse> TotalRecordsAsync(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpHeroeService.TotalRecordsRequest inValue = new Business.SOAPCSharpHeroeService.TotalRecordsRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            return ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).TotalRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpHeroeService.ExcelResponse Business.SOAPCSharpHeroeService.HeroeServiceSoap.Excel(Business.SOAPCSharpHeroeService.ExcelRequest request) {
            return base.Channel.Excel(request);
        }
        
        public Business.SOAPCSharpHeroeService.HeroeServiceExcel Excel(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpHeroeService.ExcelRequest inValue = new Business.SOAPCSharpHeroeService.ExcelRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            Business.SOAPCSharpHeroeService.ExcelResponse retVal = ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).Excel(inValue);
            return retVal.ExcelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.ExcelResponse> Business.SOAPCSharpHeroeService.HeroeServiceSoap.ExcelAsync(Business.SOAPCSharpHeroeService.ExcelRequest request) {
            return base.Channel.ExcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.ExcelResponse> ExcelAsync(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpHeroeService.ExcelRequest inValue = new Business.SOAPCSharpHeroeService.ExcelRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            return ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).ExcelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpHeroeService.PDFResponse Business.SOAPCSharpHeroeService.HeroeServiceSoap.PDF(Business.SOAPCSharpHeroeService.PDFRequest request) {
            return base.Channel.PDF(request);
        }
        
        public Business.SOAPCSharpHeroeService.HeroeServicePDF PDF(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpHeroeService.PDFRequest inValue = new Business.SOAPCSharpHeroeService.PDFRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            Business.SOAPCSharpHeroeService.PDFResponse retVal = ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).PDF(inValue);
            return retVal.PDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.PDFResponse> Business.SOAPCSharpHeroeService.HeroeServiceSoap.PDFAsync(Business.SOAPCSharpHeroeService.PDFRequest request) {
            return base.Channel.PDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpHeroeService.PDFResponse> PDFAsync(Business.SOAPCSharpHeroeService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpHeroeService.PDFRequest inValue = new Business.SOAPCSharpHeroeService.PDFRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            return ((Business.SOAPCSharpHeroeService.HeroeServiceSoap)(this)).PDFAsync(inValue);
        }
    }
}
