//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.SOAPCSharpCheckService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPCSharpCheckService.CheckServiceSoap")]
    public interface CheckServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpCheckService.MessageVO Check();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpCheckService.MessageVO> CheckAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje CheckAuthRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAuth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpCheckService.CheckAuthResponse CheckAuth(Business.SOAPCSharpCheckService.CheckAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpCheckService.CheckAuthResponse> CheckAuthAsync(Business.SOAPCSharpCheckService.CheckAuthRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titleField;
        
        private string[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("Messages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SOAPKeyAuth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckAuth", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckAuthRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpCheckService.SOAPKeyAuth SOAPKeyAuth;
        
        public CheckAuthRequest() {
        }
        
        public CheckAuthRequest(Business.SOAPCSharpCheckService.SOAPKeyAuth SOAPKeyAuth) {
            this.SOAPKeyAuth = SOAPKeyAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckAuthResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpCheckService.MessageVO CheckAuthResult;
        
        public CheckAuthResponse() {
        }
        
        public CheckAuthResponse(Business.SOAPCSharpCheckService.MessageVO CheckAuthResult) {
            this.CheckAuthResult = CheckAuthResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckServiceSoapChannel : Business.SOAPCSharpCheckService.CheckServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckServiceSoapClient : System.ServiceModel.ClientBase<Business.SOAPCSharpCheckService.CheckServiceSoap>, Business.SOAPCSharpCheckService.CheckServiceSoap {
        
        public CheckServiceSoapClient() {
        }
        
        public CheckServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Business.SOAPCSharpCheckService.MessageVO Check() {
            return base.Channel.Check();
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpCheckService.MessageVO> CheckAsync() {
            return base.Channel.CheckAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpCheckService.CheckAuthResponse Business.SOAPCSharpCheckService.CheckServiceSoap.CheckAuth(Business.SOAPCSharpCheckService.CheckAuthRequest request) {
            return base.Channel.CheckAuth(request);
        }
        
        public Business.SOAPCSharpCheckService.MessageVO CheckAuth(Business.SOAPCSharpCheckService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpCheckService.CheckAuthRequest inValue = new Business.SOAPCSharpCheckService.CheckAuthRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            Business.SOAPCSharpCheckService.CheckAuthResponse retVal = ((Business.SOAPCSharpCheckService.CheckServiceSoap)(this)).CheckAuth(inValue);
            return retVal.CheckAuthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpCheckService.CheckAuthResponse> Business.SOAPCSharpCheckService.CheckServiceSoap.CheckAuthAsync(Business.SOAPCSharpCheckService.CheckAuthRequest request) {
            return base.Channel.CheckAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpCheckService.CheckAuthResponse> CheckAuthAsync(Business.SOAPCSharpCheckService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpCheckService.CheckAuthRequest inValue = new Business.SOAPCSharpCheckService.CheckAuthRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            return ((Business.SOAPCSharpCheckService.CheckServiceSoap)(this)).CheckAuthAsync(inValue);
        }
    }
}
