//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.SOAPCSharpExampleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPCSharpExampleService.ExampleServiceSoap")]
    public interface ExampleServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje SelectRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpExampleService.SelectResponse Select(Business.SOAPCSharpExampleService.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.SelectResponse> SelectAsync(Business.SOAPCSharpExampleService.SelectRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje InsertRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpExampleService.InsertResponse Insert(Business.SOAPCSharpExampleService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.InsertResponse> InsertAsync(Business.SOAPCSharpExampleService.InsertRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje UpdateRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpExampleService.UpdateResponse Update(Business.SOAPCSharpExampleService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.UpdateResponse> UpdateAsync(Business.SOAPCSharpExampleService.UpdateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje DeleteRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpExampleService.DeleteResponse Delete(Business.SOAPCSharpExampleService.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.DeleteResponse> DeleteAsync(Business.SOAPCSharpExampleService.DeleteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ListRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpExampleService.ListResponse List(Business.SOAPCSharpExampleService.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.ListResponse> ListAsync(Business.SOAPCSharpExampleService.ListRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje TotalRecordsRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpExampleService.TotalRecordsResponse TotalRecords(Business.SOAPCSharpExampleService.TotalRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.TotalRecordsResponse> TotalRecordsAsync(Business.SOAPCSharpExampleService.TotalRecordsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ExcelRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpExampleService.ExcelResponse Excel(Business.SOAPCSharpExampleService.ExcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Excel", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.ExcelResponse> ExcelAsync(Business.SOAPCSharpExampleService.ExcelRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje PDFRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Business.SOAPCSharpExampleService.PDFResponse PDF(Business.SOAPCSharpExampleService.PDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PDF", ReplyAction="*")]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.PDFResponse> PDFAsync(Business.SOAPCSharpExampleService.PDFRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SOAPKeyAuth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExamplePDFDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] FileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("FileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleServicePDF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private ExamplePDFDTO pDFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExamplePDFDTO PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
                this.RaisePropertyChanged("PDF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titleField;
        
        private string[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("Messages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleExcelDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] FileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("FileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleServiceExcel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private ExampleExcelDTO excelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExampleExcelDTO Excel {
            get {
                return this.excelField;
            }
            set {
                this.excelField = value;
                this.RaisePropertyChanged("Excel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleServiceTotalRecords : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private long totalRecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long TotalRecords {
            get {
                return this.totalRecordsField;
            }
            set {
                this.totalRecordsField = value;
                this.RaisePropertyChanged("TotalRecords");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleServiceList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private Example[] examplesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Example[] Examples {
            get {
                return this.examplesField;
            }
            set {
                this.examplesField = value;
                this.RaisePropertyChanged("Examples");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Example : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string rutField;
        
        private string nameField;
        
        private string lastNameField;
        
        private string birthDateField;
        
        private bool activeField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleListDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
                this.RaisePropertyChanged("PageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleServiceDelete : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private bool deleteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("Delete");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleServiceUpdate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private bool updatedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("Updated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleServiceInsert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private Example exampleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Example Example {
            get {
                return this.exampleField;
            }
            set {
                this.exampleField = value;
                this.RaisePropertyChanged("Example");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleInsertDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string nameField;
        
        private string lastNameField;
        
        private string birthDateField;
        
        private bool activeField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExampleServiceSelect : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageVO messageVOField;
        
        private Example exampleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageVO MessageVO {
            get {
                return this.messageVOField;
            }
            set {
                this.messageVOField = value;
                this.RaisePropertyChanged("MessageVO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Example Example {
            get {
                return this.exampleField;
            }
            set {
                this.exampleField = value;
                this.RaisePropertyChanged("Example");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Select", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public SelectRequest() {
        }
        
        public SelectRequest(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, int id) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleServiceSelect SelectResult;
        
        public SelectResponse() {
        }
        
        public SelectResponse(Business.SOAPCSharpExampleService.ExampleServiceSelect SelectResult) {
            this.SelectResult = SelectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleInsertDTO exampleInsertDTO;
        
        public InsertRequest() {
        }
        
        public InsertRequest(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpExampleService.ExampleInsertDTO exampleInsertDTO) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.exampleInsertDTO = exampleInsertDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleServiceInsert InsertResult;
        
        public InsertResponse() {
        }
        
        public InsertResponse(Business.SOAPCSharpExampleService.ExampleServiceInsert InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.Example example;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpExampleService.Example example) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.example = example;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleServiceUpdate UpdateResult;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Business.SOAPCSharpExampleService.ExampleServiceUpdate UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, int id) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleServiceDelete DeleteResult;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(Business.SOAPCSharpExampleService.ExampleServiceDelete DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleListDTO exampleListDTO;
        
        public ListRequest() {
        }
        
        public ListRequest(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpExampleService.ExampleListDTO exampleListDTO) {
            this.SOAPKeyAuth = SOAPKeyAuth;
            this.exampleListDTO = exampleListDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleServiceList ListResult;
        
        public ListResponse() {
        }
        
        public ListResponse(Business.SOAPCSharpExampleService.ExampleServiceList ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TotalRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TotalRecordsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth;
        
        public TotalRecordsRequest() {
        }
        
        public TotalRecordsRequest(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth) {
            this.SOAPKeyAuth = SOAPKeyAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TotalRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TotalRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleServiceTotalRecords TotalRecordsResult;
        
        public TotalRecordsResponse() {
        }
        
        public TotalRecordsResponse(Business.SOAPCSharpExampleService.ExampleServiceTotalRecords TotalRecordsResult) {
            this.TotalRecordsResult = TotalRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Excel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExcelRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth;
        
        public ExcelRequest() {
        }
        
        public ExcelRequest(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth) {
            this.SOAPKeyAuth = SOAPKeyAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleServiceExcel ExcelResult;
        
        public ExcelResponse() {
        }
        
        public ExcelResponse(Business.SOAPCSharpExampleService.ExampleServiceExcel ExcelResult) {
            this.ExcelResult = ExcelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PDF", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PDFRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth;
        
        public PDFRequest() {
        }
        
        public PDFRequest(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth) {
            this.SOAPKeyAuth = SOAPKeyAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PDFResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Business.SOAPCSharpExampleService.ExampleServicePDF PDFResult;
        
        public PDFResponse() {
        }
        
        public PDFResponse(Business.SOAPCSharpExampleService.ExampleServicePDF PDFResult) {
            this.PDFResult = PDFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExampleServiceSoapChannel : Business.SOAPCSharpExampleService.ExampleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExampleServiceSoapClient : System.ServiceModel.ClientBase<Business.SOAPCSharpExampleService.ExampleServiceSoap>, Business.SOAPCSharpExampleService.ExampleServiceSoap {
        
        public ExampleServiceSoapClient() {
        }
        
        public ExampleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExampleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpExampleService.SelectResponse Business.SOAPCSharpExampleService.ExampleServiceSoap.Select(Business.SOAPCSharpExampleService.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public Business.SOAPCSharpExampleService.ExampleServiceSelect Select(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, int id) {
            Business.SOAPCSharpExampleService.SelectRequest inValue = new Business.SOAPCSharpExampleService.SelectRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.id = id;
            Business.SOAPCSharpExampleService.SelectResponse retVal = ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).Select(inValue);
            return retVal.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.SelectResponse> Business.SOAPCSharpExampleService.ExampleServiceSoap.SelectAsync(Business.SOAPCSharpExampleService.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.SelectResponse> SelectAsync(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, int id) {
            Business.SOAPCSharpExampleService.SelectRequest inValue = new Business.SOAPCSharpExampleService.SelectRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.id = id;
            return ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpExampleService.InsertResponse Business.SOAPCSharpExampleService.ExampleServiceSoap.Insert(Business.SOAPCSharpExampleService.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public Business.SOAPCSharpExampleService.ExampleServiceInsert Insert(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpExampleService.ExampleInsertDTO exampleInsertDTO) {
            Business.SOAPCSharpExampleService.InsertRequest inValue = new Business.SOAPCSharpExampleService.InsertRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.exampleInsertDTO = exampleInsertDTO;
            Business.SOAPCSharpExampleService.InsertResponse retVal = ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).Insert(inValue);
            return retVal.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.InsertResponse> Business.SOAPCSharpExampleService.ExampleServiceSoap.InsertAsync(Business.SOAPCSharpExampleService.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.InsertResponse> InsertAsync(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpExampleService.ExampleInsertDTO exampleInsertDTO) {
            Business.SOAPCSharpExampleService.InsertRequest inValue = new Business.SOAPCSharpExampleService.InsertRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.exampleInsertDTO = exampleInsertDTO;
            return ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpExampleService.UpdateResponse Business.SOAPCSharpExampleService.ExampleServiceSoap.Update(Business.SOAPCSharpExampleService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public Business.SOAPCSharpExampleService.ExampleServiceUpdate Update(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpExampleService.Example example) {
            Business.SOAPCSharpExampleService.UpdateRequest inValue = new Business.SOAPCSharpExampleService.UpdateRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.example = example;
            Business.SOAPCSharpExampleService.UpdateResponse retVal = ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).Update(inValue);
            return retVal.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.UpdateResponse> Business.SOAPCSharpExampleService.ExampleServiceSoap.UpdateAsync(Business.SOAPCSharpExampleService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.UpdateResponse> UpdateAsync(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpExampleService.Example example) {
            Business.SOAPCSharpExampleService.UpdateRequest inValue = new Business.SOAPCSharpExampleService.UpdateRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.example = example;
            return ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpExampleService.DeleteResponse Business.SOAPCSharpExampleService.ExampleServiceSoap.Delete(Business.SOAPCSharpExampleService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public Business.SOAPCSharpExampleService.ExampleServiceDelete Delete(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, int id) {
            Business.SOAPCSharpExampleService.DeleteRequest inValue = new Business.SOAPCSharpExampleService.DeleteRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.id = id;
            Business.SOAPCSharpExampleService.DeleteResponse retVal = ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).Delete(inValue);
            return retVal.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.DeleteResponse> Business.SOAPCSharpExampleService.ExampleServiceSoap.DeleteAsync(Business.SOAPCSharpExampleService.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.DeleteResponse> DeleteAsync(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, int id) {
            Business.SOAPCSharpExampleService.DeleteRequest inValue = new Business.SOAPCSharpExampleService.DeleteRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.id = id;
            return ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpExampleService.ListResponse Business.SOAPCSharpExampleService.ExampleServiceSoap.List(Business.SOAPCSharpExampleService.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public Business.SOAPCSharpExampleService.ExampleServiceList List(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpExampleService.ExampleListDTO exampleListDTO) {
            Business.SOAPCSharpExampleService.ListRequest inValue = new Business.SOAPCSharpExampleService.ListRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.exampleListDTO = exampleListDTO;
            Business.SOAPCSharpExampleService.ListResponse retVal = ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).List(inValue);
            return retVal.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.ListResponse> Business.SOAPCSharpExampleService.ExampleServiceSoap.ListAsync(Business.SOAPCSharpExampleService.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.ListResponse> ListAsync(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth, Business.SOAPCSharpExampleService.ExampleListDTO exampleListDTO) {
            Business.SOAPCSharpExampleService.ListRequest inValue = new Business.SOAPCSharpExampleService.ListRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            inValue.exampleListDTO = exampleListDTO;
            return ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).ListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpExampleService.TotalRecordsResponse Business.SOAPCSharpExampleService.ExampleServiceSoap.TotalRecords(Business.SOAPCSharpExampleService.TotalRecordsRequest request) {
            return base.Channel.TotalRecords(request);
        }
        
        public Business.SOAPCSharpExampleService.ExampleServiceTotalRecords TotalRecords(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpExampleService.TotalRecordsRequest inValue = new Business.SOAPCSharpExampleService.TotalRecordsRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            Business.SOAPCSharpExampleService.TotalRecordsResponse retVal = ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).TotalRecords(inValue);
            return retVal.TotalRecordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.TotalRecordsResponse> Business.SOAPCSharpExampleService.ExampleServiceSoap.TotalRecordsAsync(Business.SOAPCSharpExampleService.TotalRecordsRequest request) {
            return base.Channel.TotalRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.TotalRecordsResponse> TotalRecordsAsync(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpExampleService.TotalRecordsRequest inValue = new Business.SOAPCSharpExampleService.TotalRecordsRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            return ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).TotalRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpExampleService.ExcelResponse Business.SOAPCSharpExampleService.ExampleServiceSoap.Excel(Business.SOAPCSharpExampleService.ExcelRequest request) {
            return base.Channel.Excel(request);
        }
        
        public Business.SOAPCSharpExampleService.ExampleServiceExcel Excel(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpExampleService.ExcelRequest inValue = new Business.SOAPCSharpExampleService.ExcelRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            Business.SOAPCSharpExampleService.ExcelResponse retVal = ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).Excel(inValue);
            return retVal.ExcelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.ExcelResponse> Business.SOAPCSharpExampleService.ExampleServiceSoap.ExcelAsync(Business.SOAPCSharpExampleService.ExcelRequest request) {
            return base.Channel.ExcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.ExcelResponse> ExcelAsync(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpExampleService.ExcelRequest inValue = new Business.SOAPCSharpExampleService.ExcelRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            return ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).ExcelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Business.SOAPCSharpExampleService.PDFResponse Business.SOAPCSharpExampleService.ExampleServiceSoap.PDF(Business.SOAPCSharpExampleService.PDFRequest request) {
            return base.Channel.PDF(request);
        }
        
        public Business.SOAPCSharpExampleService.ExampleServicePDF PDF(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpExampleService.PDFRequest inValue = new Business.SOAPCSharpExampleService.PDFRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            Business.SOAPCSharpExampleService.PDFResponse retVal = ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).PDF(inValue);
            return retVal.PDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.PDFResponse> Business.SOAPCSharpExampleService.ExampleServiceSoap.PDFAsync(Business.SOAPCSharpExampleService.PDFRequest request) {
            return base.Channel.PDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<Business.SOAPCSharpExampleService.PDFResponse> PDFAsync(Business.SOAPCSharpExampleService.SOAPKeyAuth SOAPKeyAuth) {
            Business.SOAPCSharpExampleService.PDFRequest inValue = new Business.SOAPCSharpExampleService.PDFRequest();
            inValue.SOAPKeyAuth = SOAPKeyAuth;
            return ((Business.SOAPCSharpExampleService.ExampleServiceSoap)(this)).PDFAsync(inValue);
        }
    }
}
